platform :ios, '12.1'

use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'FolioReaderKit', path: '../'
end

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'Example' do
  shared_pods
end

target 'Storyboard-Example' do
	shared_pods
end

target 'MultipleInstance-Example' do
    shared_pods
end

target 'FolioReaderTests' do
  shared_pods
  testing_pods
end
